name: TerritoryBeacons
version: '1.8'
main: com.Lino.territoryBeacons.TerritoryBeacons
api-version: '1.21'
author: Lino
description: A territorial claiming system based on powered beacons.
softdepend: [Pl3xMap, Vault]

commands:
  territory:
    description: Main command to manage territories.
    usage: /territory <subcommand>
    aliases: [terr, t]
    permission: territory.use

permissions:
  territory.use:
    description: Basic permission to use territory commands.
    default: true

  territory.admin:
    description: Admin permission to bypass protections.
    default: op

  territory.create:
    description: Allows creating territories.
    default: true

  territory.trust:
    description: Allows adding trusted players.
    default: true

  territory.setname:
    description: Allows setting a name for the territory.
    default: true

  territory.*:
    description: All territory permissions.
    default: op
    children:
      territory.use: true
      territory.admin: true
      territory.create: true
      territory.trust: true
      territory.setname: true